"""Prepare and train a lightweight YOLO oriented-card detector.

The script writes deterministic split lists next to the dataset without copying the
generated images or labels. It relies on Ultralytics as an optional dependency.
"""

from __future__ import annotations

import argparse
import random
from pathlib import Path


def import_runtime():
    """Load the optional training dependencies only when a training run starts."""
    try:
        import torch
        from ultralytics import YOLO
    except ImportError as error:
        raise SystemExit(
            "Missing optional training dependencies. Install them with:\n"
            "uv sync --extra training\n"
            "Then rerun this command."
        ) from error
    return torch, YOLO


def select_device(torch, requested_device: str) -> str:
    """Use the requested device or select the best locally available accelerator."""
    if requested_device != "auto":
        return requested_device
    if torch.cuda.is_available():
        return "0"
    if torch.backends.mps.is_available():
        return "mps"
    return "cpu"


def validate_dataset(dataset_dir: Path) -> list[Path]:
    """Return valid images after checking corresponding YOLO-OBB label files."""
    images_dir = dataset_dir / "images"
    labels_dir = dataset_dir / "labels"
    images = sorted(images_dir.glob("*.jpg"))
    if not images:
        raise ValueError(f"No JPG images found in {images_dir}")

    missing_labels = [
        image for image in images if not (labels_dir / f"{image.stem}.txt").is_file()
    ]
    if missing_labels:
        raise ValueError(
            f"Missing labels for {len(missing_labels)} images; first: {missing_labels[0].name}"
        )

    for image in images:
        label_path = labels_dir / f"{image.stem}.txt"
        for line_number, line in enumerate(
            label_path.read_text(encoding="utf-8").splitlines(), start=1
        ):
            fields = line.split()
            if len(fields) != 9:
                raise ValueError(
                    f"{label_path}:{line_number} must have class ID plus 8 OBB coordinates"
                )
            try:
                coordinates = [float(value) for value in fields[1:]]
            except ValueError as error:
                raise ValueError(
                    f"{label_path}:{line_number} has non-numeric OBB coordinates"
                ) from error
            if not all(0.0 <= value <= 1.0 for value in coordinates):
                raise ValueError(
                    f"{label_path}:{line_number} has OBB coordinates outside [0, 1]"
                )
    return images


def write_split_files(
    dataset_dir: Path, images: list[Path], validation_fraction: float, seed: int
) -> Path:
    """Create deterministic absolute image lists and an Ultralytics dataset YAML."""
    if not 0.0 < validation_fraction < 1.0:
        raise ValueError("validation_fraction must be between zero and one")

    shuffled_images = images.copy()
    random.Random(seed).shuffle(shuffled_images)
    validation_count = max(1, round(len(shuffled_images) * validation_fraction))
    validation_images = sorted(shuffled_images[:validation_count])
    training_images = sorted(shuffled_images[validation_count:])
    if not training_images:
        raise ValueError("Validation fraction leaves no training images")

    splits_dir = dataset_dir / "splits"
    splits_dir.mkdir(exist_ok=True)
    train_list = splits_dir / "train.txt"
    validation_list = splits_dir / "val.txt"
    train_list.write_text(
        "\n".join(str(image.resolve()) for image in training_images) + "\n",
        encoding="utf-8",
    )
    validation_list.write_text(
        "\n".join(str(image.resolve()) for image in validation_images) + "\n",
        encoding="utf-8",
    )

    yaml_path = dataset_dir / "dataset.yaml"
    yaml_path.write_text(
        "# Generated by detector_training/train_yolo_obb.py\n"
        f"path: {dataset_dir.resolve()}\n"
        "train: splits/train.txt\n"
        "val: splits/val.txt\n"
        "names:\n"
        "  0: card\n",
        encoding="utf-8",
    )
    print(f"Prepared split: train={len(training_images)}, val={len(validation_images)}")
    return yaml_path


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Train a lightweight YOLO OBB card detector."
    )
    parser.add_argument(
        "--dataset-dir",
        type=Path,
        default=Path("data/detector_training_data/synthetic/mtg_mobile_v2"),
    )
    parser.add_argument(
        "--model", default="yolo11n-obb.pt", help="Pretrained Ultralytics OBB model."
    )
    parser.add_argument("--epochs", type=int, default=10)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument(
        "--batch", type=int, default=16, help="Use -1 for CUDA auto-batch."
    )
    parser.add_argument(
        "--device",
        default="auto",
        help="auto, mps, cpu, CUDA index, or CUDA device list.",
    )
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--validation-fraction", type=float, default=0.15)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--output-dir", type=Path, default=Path("runs/obb"))
    parser.add_argument("--name", default="mtg_v1_yolo11n_obb")
    parser.add_argument("--resume", action="store_true")
    args = parser.parse_args()

    if args.epochs <= 0 or args.imgsz <= 0 or args.workers < 0:
        parser.error(
            "--epochs and --imgsz must be positive; --workers cannot be negative"
        )

    images = validate_dataset(args.dataset_dir)
    dataset_yaml = write_split_files(
        args.dataset_dir, images, args.validation_fraction, args.seed
    )
    torch, YOLO = import_runtime()
    device = select_device(torch, args.device)
    print(f"Training on {device} with {args.model}; dataset config: {dataset_yaml}")

    model = YOLO(args.model)
    results = model.train(
        data=str(dataset_yaml),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=device,
        workers=args.workers,
        project=str(args.output_dir),
        name=args.name,
        seed=args.seed,
        deterministic=True,
        pretrained=True,
        patience=15,
        cos_lr=True,
        close_mosaic=10,
        degrees=45.0,
        translate=0.08,
        scale=0.30,
        perspective=0.0005,
        fliplr=0.5,
        hsv_h=0.015,
        hsv_s=0.5,
        hsv_v=0.35,
        resume=args.resume,
    )
    print(f"Training complete. Results: {results.save_dir}")


if __name__ == "__main__":
    main()
